// port-lint: source model/task.rs
@file:OptIn(ExperimentalUnsignedTypes::class)

package io.github.kotlinmania.rmcp.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/**
 * Canonical task lifecycle status as defined by SEP-1686.
 */
@Serializable
enum class TaskStatus {
    /**
     * The receiver accepted the request and is currently working on it.
     */
    @SerialName("working")
    Working,

    /**
     * The receiver requires additional input before work can continue.
     */
    @SerialName("input_required")
    InputRequired,

    /**
     * The underlying operation completed successfully and the result is ready.
     */
    @SerialName("completed")
    Completed,

    /**
     * The underlying operation failed and will not continue.
     */
    @SerialName("failed")
    Failed,

    /**
     * The task was cancelled and will not continue processing.
     */
    @SerialName("cancelled")
    Cancelled,
}

/**
 * Final result for a succeeded task, returned from `tasks/result`.
 */
@Serializable
data class TaskResult(
    /**
     * MIME type or custom content-type identifier.
     */
    val contentType: String,
    /**
     * The actual result payload, matching the underlying request's schema.
     */
    val value: JsonElement,
    /**
     * Optional short summary for UI surfaces.
     */
    val summary: String? = null,
)

/**
 * Primary Task object that surfaces metadata during the task lifecycle.
 */
@Serializable
data class Task(
    /**
     * Unique task identifier generated by the receiver.
     */
    val taskId: String = "",
    /**
     * Current lifecycle status (see [TaskStatus]).
     */
    val status: TaskStatus = TaskStatus.Working,
    /**
     * Optional human-readable status message for UI surfaces.
     */
    val statusMessage: String? = null,
    /**
     * ISO-8601 creation timestamp.
     */
    val createdAt: String = "",
    /**
     * ISO-8601 timestamp for the most recent status change.
     */
    val lastUpdatedAt: String? = null,
    /**
     * Retention window in milliseconds that the receiver agreed to honor.
     */
    val ttl: ULong? = null,
    /**
     * Suggested polling interval in milliseconds.
     */
    val pollInterval: ULong? = null,
)

/**
 * Wrapper returned by task-augmented requests, CreateTaskResult in SEP-1686.
 */
@Serializable
data class CreateTaskResult(
    val task: Task,
)

/**
 * Paginated list of tasks.
 */
@Serializable
data class TaskList(
    val tasks: List<Task>,
    val nextCursor: String? = null,
    val total: ULong? = null,
)
